# Note: Remove the baseurl in order to deploy at the domain root
baseurl:
title: RJ's blog
# Whether the header (with large title and subtitle) should be displayed
header: false
subtitle: What do images do to us? And how do they do it?
author: RJ
description: 
show_author: true
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
# permalink: /blog/:categories/:year/:month/:day/:title.html
timezone: America/Los_Angeles
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
plugins:
  - jekyll-feed
  - jekyll-theme-tufte
